### ISSUE TITLE
on highlight change

### ISSUE THREAD

**Issue by vauradkar** [kang-sw/egui-data-table#24]
I want a callback when a row gets highlighted or unhighlighted. Given, current fn `on_highlight_cell` is not called from any place, would you be willing to accept a patch like this? https://github.com/kang-sw/egui-data-table/compare/master...vauradkar:egui-data-table:master

**Comment by kang-sw** [comment]
Thank you for raising this and for considering making a patch!

Feel free to go ahead and create a pull request. I had a quick look at your changes and overall, it seems reasonable. There is a slight concern about comparing the entire selection every time, but since the callback is only invoked when the cursor selection command is triggered, it looks good and should work well.

As this crate has primarily been for my own dog-fooding, many features are still missing. Approaches like these that enhance the UI-response callbacks are very welcome and add a lot of value.

One small suggestion: the new trait API you added, on_highlight_change, currently delivers an array of row references directly. Would you consider including the column number in the tuple for better clarity and flexibility?

Looking forward to seeing your PR! 😊

**Comment by vauradkar** [comment]
I created a pull request. PTAL.

On including column, I can update the PR to include column number. But my current use case to register a callback when one or more rows (all columns in those rows) are selected. It doesn't make much sense to include column number or for that matter an array of column number. WDYT?

**Comment by kang-sw** [comment]
Well I agree that this doesn't make sense right now. Initially thought that was tiny fix on signature as the selection already includes column numbers, however, it seems it would add overhead on performance/usability both without careful design. 

I'll check the PR. Thanks a lot!

**Comment by vauradkar** [comment]
Fixed with https://github.com/kang-sw/egui-data-table/pull/27
